#!/bin/sh

# Killing any possible previous processes
killall -q picom
killall -q sxhkd

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5

pgrep -x sxhkd > /dev/null || sxhkd &
picom & 
~/.config/polybar/launch.sh &
feh --bg-fill ~/.config/wallpapers/neon.png &
xrdb merge ~/.Xresources &
xinput set-prop "DELL0A6E:00 06CB:CE81 Touchpad" "libinput Disable While Typing Enabled" 0 &
flameshot &

# Mouse configs
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Settings

bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#353b45"
# bspc config focused_border_color    "#E43F5A"  
# bspc config normal_border_color     "#162447"

bspc config top_padding         25
bspc config border_width         2
bspc config window_gap          13

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
